{% set name = "alteryx-open-src-update-checker" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 36b67459a822d695dfe9f41bfdd73bf28425d89b0e146f66e2c0bb6e52466f62


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - ALTERYX_OPEN_SRC_UPDATE_CHECKER=False

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.22.0
test:
  imports:
    - alteryx_open_src_update_checker
  requires:
    - pytest ==5.0.0
    - featuretools ==0.7.1
    - composeml ==0.6.0
    - evalml ==0.14.1
    - woodwork ==0.0.11
    - mock >=3.0.5
  source_files:
    - alteryx_open_src_update_checker/tests/*
  commands:
    - pytest alteryx_open_src_update_checker/tests

about:
  home: https://github.com/alteryx/alteryx-open-src-update-checker/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an update checker for alteryx open source libraries

extra:
  recipe-maintainers:
    - gsheni
    - freddyaboulton
    - thehomebrewnerd
    - rwedge
    - tamargrey
    - tuethan1999
    - davesque
    - jeff-hernandez
    - angela97lin
